#Read Mcaffe Logs from file generated by command mode and forward to splunk UDP port.

import sys
import time
import os
import socket

print "Extracting events\n"

UDP_IP = "127.0.0.1"
UDP_PORT = 5555

os.system("cat a.txt > log.log");
combiner = ""
line_counter = 0
event_counter = 0
with open('log.log', 'rb') as f:
	for i,line in enumerate(f):
		if i>=3:
			if line.strip() != "":
				line = "".join(line.split())+","
				if event_counter>=1:
					combiner += line.replace(":","=")
				else:
					combiner += line
				event_counter+=1
			else:
				print combiner
				s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, 0)
				s.connect((UDP_IP, UDP_PORT))
				s.send(combiner)
				s.close()
				combiner = ""
				line_counter+=1
				event_counter=0
				print "Sent Packets: "+str(line_counter)
